### ISSUE TITLE
FutureWarning: read_table is deprecated

### ISSUE THREAD

**Issue by p-himik** [kszucs/pandahouse#20]
https://github.com/kszucs/pandahouse/blob/master/pandahouse/convert.py#L78 still uses `read_table` which results in this warning with pandas 0.24.2:
```
/.../lib/python3.7/site-packages/pandahouse/convert.py:77: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  na_values=set(), keep_default_na=False, **kwargs)
```

**Comment by haakonvt** [comment]
https://github.com/kszucs/pandahouse/pull/18#issue-253091260

**Comment by haakonvt** [comment]
As of 0.25, it is undeprecated...

**Comment by p-himik** [comment]
And `pandahouse` doesn't specify any particular `pandas` version, so I guess it's all good now.
