### ISSUE TITLE
项目不维护了，很多坑，别跳了

### ISSUE THREAD

**Issue by happybeta** [kszucs/pandahouse#37]

**Comment by kszucs** [comment]
Please prefer english. I assume it means something like the project is not maintained anymore. 

Sadly indeed, I don't have time to actively maintain/develop it. On the other hand I can suggest you to try using the [ibis-project](http://github.com/ibis-project/ibis/) instead which has a fairly complete clickhouse support and you can retrieve various query results in not just pandas but in arrow formats as well.
